version: '3'

services:
  server:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
  client:
    build: ./client
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
