name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      IMAGE_NAME_SERVER: lenaerts/server
      IMAGE_NAME_CLIENT: lenaerts/client

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build server image
        uses: docker/build-push-action@v2
        with:
          context: ./server
          push: true
          tags: ${{ env.IMAGE_NAME_SERVER }}

      - name: Build client image
        uses: docker/build-push-action@v2
        with:
          context: ./client
          push: true
          tags: ${{ env.IMAGE_NAME_CLIENT }}

      - name: Deploy to Kubernetes
        uses: appleboy/kubectl-action@master
        config_file: {{env.KUBE_CONFIG}}
        with:
          args: apply -f ./kubernetes

