name: Pipelines
on:
  push:
    branches:
      - main
jobs:
  deployment:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            rm -rf school-se-for-the-cloud
            git clone git@github.com:MartinLenaerts/school-se-for-the-cloud.git
            cd school-se-for-the-cloud
            docker-compose up -d --build